# =======================================================================================
# Atomscistudio on Windows is built and tested using Visual Studio Community Version.
# Many open source softwares provide binaries built with MSVC, as the eula of 
# MSVC Community Version is open source friendly. Namely MSVC Community Version can be 
# used in the development of OSI approved open source softwares.
# =======================================================================================
name: Build for Windows using MSVC Community Version
on:
  push:
    branches: [ master ]
    tags:
      - 'v*'
  pull_request:
    branches: [ master ]
jobs:
  build-for-windows:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-2019]
        qt_version: ["6.3.0"]
        qt_arch: ["win64_msvc2019_64"]
    env:
      executable: atomscistudio
    steps:
      - name: Caching MSVC Community Version
        id: cache-msvc-community
        uses: actions/cache@v3  
        with:
          path: "C:/Program Files (x86)/Microsoft Visual Studio/2019/Community"
          key: ${{ runner.os }}-cache-msvc-community-on-2022.06.16-version-1
      - name: Set up Visual Studio 2019 community version
        if: steps.cache-msvc-community.outputs.cache-hit != 'true'
        run: |
          choco install visualstudio2019community --package-parameters "--allWorkloads --includeRecommended --passive"
          & "C:/Program Files (x86)/Microsoft Visual Studio/2019/Community/VC/Auxiliary/Build/vcvars64.bat"
        shell: powershell
      - name: Install ninja
        uses: seanmiddleditch/gha-setup-ninja@master
        with:
          destination: "C:/Softwares/ninja"
      - name: Caching vcpkg binary caches
        id: cache-vcpkg
        uses: actions/cache@v3
        with:
          path: C:\Users\runneradmin\AppData\Local\vcpkg\archives
          key: ${{ runner.os }}-cache-vcpkg-on-2022.06.16-version-1
      - name: Caching built packages
        id: cache-built-packages
        uses: actions/cache@v3
        with:
          path: |
            C:\Softwares\gtest
            C:\Softwares\yaml-cpp
            C:\Softwares\libssh2
            C:\Softwares\armadillo
            C:\Softwares\atomsciflow
          key: ${{ runner.os }}-cache-built-packages-on-2022.06.16-version-1
      - name: Install Open CASCADE
        id: install-opencascade
        run: |
          & "C:/Program Files (x86)/Microsoft Visual Studio/2019/Community/VC/Auxiliary/Build/vcvars64.bat"
          vcpkg install opencascade:x64-windows --binarysource=default,readwrite
          $prefix_ = "${env:VCPKG_INSTALLATION_ROOT}/packages/opencascade_x64-windows"

          echo "::set-output name=prefix::${prefix_}"
        shell: powershell
      - name: Install OpenSSL
        run: |
          choco install openssl
          choco upgrade openssl.light        
        shell: powershell
      - name: Install Qt
        uses: jurplel/install-qt-action@v2.14.0
        with:
          host: 'windows'
          version: ${{ matrix.qt_version }} 
          arch: ${{ matrix.qt_arch }}
          target: 'desktop'
          aqtversion: '==2.1.0'
          modules: 'qt3d'
      - name: Install Boost
        id: install-boost
        uses: MarkusJx/install-boost@v2.2.0
        with:
          boost_version: 1.78.0
          platform_version: 2019
          boost_install_dir: "C:/Softwares"
          toolset: msvc
      - name: Install googletest
        id: install-gtest
        run: |
          & "C:/Program Files (x86)/Microsoft Visual Studio/2019/Community/VC/Auxiliary/Build/vcvars64.bat"
          $prefix_ = "C:/Softwares/gtest"
          
          if ("${{ steps.cache-built-packages.outputs.cache-hit }}" -notlike "true") {
            Invoke-WebRequest -Uri https://github.com/google/googletest/archive/refs/tags/release-1.11.0.tar.gz -OutFile release-1.11.0.tar.gz
            tar -xf release-1.11.0.tar.gz

            cmake googletest-release-1.11.0 -B build_gtest -G "Visual Studio 16 2019" -A x64
            cmake --build build_gtest --config Release --parallel 4
            cmake --install build_gtest
          }
          echo "::set-output name=prefix::${prefix_}"
        shell: powershell
      - name: Install yaml-cpp
        id: install-yaml-cpp
        run: |
          & "C:/Program Files (x86)/Microsoft Visual Studio/2019/Community/VC/Auxiliary/Build/vcvars64.bat"
          $prefix_ = "C:/Softwares/yaml-cpp"
          
          if ("${{ steps.cache-built-packages.outputs.cache-hit }}" -notlike "true") {
            Invoke-WebRequest -Uri https://github.com/jbeder/yaml-cpp/archive/refs/tags/yaml-cpp-0.7.0.tar.gz -OutFile yaml-cpp-0.7.0.tar.gz
            tar -xf yaml-cpp-0.7.0.tar.gz

            cmake yaml-cpp-yaml-cpp-0.7.0 -B build_yaml_cpp -G "Visual Studio 16 2019" -A x64 -DCMAKE_INSTALL_PREFIX="${prefix_}" -DCMAKE_BUILD_TYPE=Release -DYAML_BUILD_SHARED_LIBS=ON
            cmake --build build_yaml_cpp --config Release --parallel 4 
            cmake --install build_yaml_cpp
          }
          echo "::set-output name=prefix::${prefix_}"
        shell: powershell
      - name: Install libssh2
        id: install-libssh2
        run: |
          & "C:/Program Files (x86)/Microsoft Visual Studio/2019/Community/VC/Auxiliary/Build/vcvars64.bat"
          $prefix_ = "C:/Softwares/libssh2"

          if ("${{ steps.cache-built-packages.outputs.cache-hit }}" -notlike "true") {
            Invoke-WebRequest -Uri https://github.com/libssh2/libssh2/releases/download/libssh2-1.10.0/libssh2-1.10.0.tar.gz -OutFile libssh2-1.10.0.tar.gz
            tar -xf libssh2-1.10.0.tar.gz

            cmake libssh2-1.10.0 -B build_libssh2 -G "Visual Studio 16 2019" -A x64 -DCMAKE_INSTALL_PREFIX="${prefix_}" -DCMAKE_BUILD_TYPE=Release 
            cmake --build build_libssh2 --config Release --parallel 4
            cmake --install build_libssh2
          }
          echo "::set-output name=prefix::${prefix_}"
        shell: powershell 
      - name: Install armadillo
        id: install-armadillo
        run: |
          & "C:/Program Files (x86)/Microsoft Visual Studio/2019/Community/VC/Auxiliary/Build/vcvars64.bat"
          $prefix_ = "C:/Softwares/armadillo"

          if ("${{ steps.cache-built-packages.outputs.cache-hit }}" -notlike "true") {
            
            Invoke-WebRequest -Uri https://jztkft.dl.sourceforge.net/project/arma/armadillo-10.8.2.tar.xz -OutFile armadillo-10.8.2.tar.xz

            # choco install 7zip.install --force
            7z x armadillo-10.8.2.tar.xz
            tar -xf armadillo-10.8.2.tar

            cmake armadillo-10.8.2 -B build_armadillo -G "Visual Studio 16 2019" -A x64 -DCMAKE_INSTALL_PREFIX="${prefix_}" -DCMAKE_BUILD_TYPE=Release
            cmake --build build_armadillo --config Release --parallel 4
            cmake --install build_armadillo
          }
          echo "::set-output name=prefix::${prefix_}"
        shell: powershell
      - name: Install Atomsciflow
        id: install-atomsciflow
        run: |
          & "C:/Program Files (x86)/Microsoft Visual Studio/2019/Community/VC/Auxiliary/Build/vcvars64.bat"
          $prefix_ = "C:/Softwares/atomsciflow"

          if ("${{ steps.cache-built-packages.outputs.cache-hit }}" -notlike "true") {
            # "${{ steps.xxx.outputs.cache-hit }}" could be "" or "true"
            git clone https://github.com/deqitang/build-test-atomsciflow.git
            cmake build-test-atomsciflow -B build_atomsciflow -DBUILD_CMD=OFF -DBUILD_TEST=OFF -G "Visual Studio 16 2019" -DCMAKE_INSTALL_PREFIX="$prefix_" -DCMAKE_PREFIX_PATH="${{ steps.install-armadillo.outputs.prefix }};${{ steps.install-libssh2.outputs.prefix }}" -DYAML_CPP_PKGCONFIG_DIR="${{ steps.install-yaml-cpp.outputs.prefix }}/share/pkgconfig" -DGTEST_ROOT="${{ steps.install-gtest.outputs.prefix }}"
            cmake --build build_atomsciflow --config Release --parallel 4
            cmake --install build_atomsciflow
          }
          echo "::set-output name=prefix::${prefix_}"
        env:
          BOOST_ROOT: ${{ steps.install-boost.outputs.BOOST_ROOT }}
        shell: powershell
      - uses: actions/checkout@v2
        with:
          fetch-depth: 1
      - name: Build for Windows with MSVC
        run: |
          & "C:/Program Files (x86)/Microsoft Visual Studio/2019/Community/VC/Auxiliary/Build/vcvars64.bat"
          cmake -B build_atomscistudio -G 'Visual Studio 16 2019' -DCMAKE_PREFIX_PATH="${{ steps.install-armadillo.outputs.prefix }};${{ steps.install-libssh2.outputs.prefix }};${{ steps.install-opencascade.outputs.prefix }};${{ steps.install-atomsciflow.outputs.prefix }}" -DYAML_CPP_PKGCONFIG_DIR="${{ steps.install-yaml-cpp.outputs.prefix }}/share/pkgconfig"
          cmake --build build_atomscistudio --config Release --parallel 4
        env:
          BOOST_ROOT: ${{ steps.install-boost.outputs.BOOST_ROOT }}  
        shell: powershell
      - name: packaging
        id: packaging
        shell: powershell
        env:
          archive_name: atomscistudio-${{ matrix.qt_arch }}
        run: |
          New-Item -ItemType Directory ${env:archive_name}
          Copy-Item build_atomscistudio\Release\${env:executable}'.exe' ${env:archive_name}\${env:executable}'.exe'
          windeployqt ${env:archive_name}\${env:executable}'.exe' --verbose=2 --compiler-runtime
          ldd ${env:archive_name}\${env:executable}'.exe'
          Copy-Item README.md ${env:archive_name}\README.md
          Copy-Item LICENSE ${env:archive_name}\LICENSE
          Copy-Item NOTICE ${env:archive_name}\NOTICE
          New-Item -ItemType Directory ${env:archive_name}\third_party\license
          Copy-Item third_party\license\* ${env:archive_name}\third_party\license\ -Recurse
          Copy-Item "C:/Program Files/OpenSSL-Win64/libcrypto-1_1-x64.dll" ${env:archive_name}\
          Copy-Item "C:/Program Files/OpenSSL-Win64/libssl-1_1-x64.dll" ${env:archive_name}\
          Copy-Item "C:/Softwares/yaml-cpp/bin/yaml-cpp.dll" ${env:archive_name}\
          Copy-Item "${env:VCPKG_INSTALLATION_ROOT}/packages/opencascade_x64-windows/bin/TKV3d.dll" ${env:archive_name}\
          Copy-Item "${env:VCPKG_INSTALLATION_ROOT}/packages/opencascade_x64-windows/bin/TKTopAlgo.dll" ${env:archive_name}\
          Copy-Item "${env:VCPKG_INSTALLATION_ROOT}/packages/opencascade_x64-windows/bin/TKService.dll" ${env:archive_name}\
          Copy-Item "${env:VCPKG_INSTALLATION_ROOT}/packages/opencascade_x64-windows/bin/TKPrim.dll" ${env:archive_name}\
          Copy-Item "${env:VCPKG_INSTALLATION_ROOT}/packages/opencascade_x64-windows/bin/TKOpenGl.dll" ${env:archive_name}\
          Copy-Item "${env:VCPKG_INSTALLATION_ROOT}/packages/opencascade_x64-windows/bin/TKernel.dll" ${env:archive_name}\
          Copy-Item "${env:VCPKG_INSTALLATION_ROOT}/packages/opencascade_x64-windows/bin/TKBRep.dll" ${env:archive_name}\
          Copy-Item "${env:VCPKG_INSTALLATION_ROOT}/packages/opencascade_x64-windows/bin/TKGeomBase.dll" ${env:archive_name}\
          Copy-Item "${env:VCPKG_INSTALLATION_ROOT}/packages/opencascade_x64-windows/bin/TKGeomAlgo.dll" ${env:archive_name}\
          Copy-Item "${env:VCPKG_INSTALLATION_ROOT}/packages/opencascade_x64-windows/bin/TKG3d.dll" ${env:archive_name}\
          Copy-Item "${env:VCPKG_INSTALLATION_ROOT}/packages/opencascade_x64-windows/bin/TKG2d.dll" ${env:archive_name}\
          Copy-Item "${env:VCPKG_INSTALLATION_ROOT}/packages/opencascade_x64-windows/bin/TKMath.dll" ${env:archive_name}\
          Copy-Item "${env:VCPKG_INSTALLATION_ROOT}/packages/opencascade_x64-windows/bin/TKMesh.dll" ${env:archive_name}\
          Copy-Item "${env:VCPKG_INSTALLATION_ROOT}/packages/opencascade_x64-windows/bin/TKHLR.dll" ${env:archive_name}\
          Copy-Item "${env:VCPKG_INSTALLATION_ROOT}/packages/opencascade_x64-windows/bin/TKShHealing.dll" ${env:archive_name}\
          Copy-Item "${env:VCPKG_INSTALLATION_ROOT}/packages/freetype_x64-windows/bin/freetype.dll" ${env:archive_name}\
          Copy-Item "${env:VCPKG_INSTALLATION_ROOT}/packages/bzip2_x64-windows/bin/bz2.dll" ${env:archive_name}\
          Copy-Item "${env:VCPKG_INSTALLATION_ROOT}/packages/libpng_x64-windows/bin/libpng16.dll" ${env:archive_name}\
          Copy-Item "${env:VCPKG_INSTALLATION_ROOT}/packages/brotli_x64-windows/bin/brotlidec.dll" ${env:archive_name}\
          Copy-Item "${env:VCPKG_INSTALLATION_ROOT}/packages/brotli_x64-windows/bin/brotlicommon.dll" ${env:archive_name}\
          Compress-Archive -Path ${env:archive_name} ${env:archive_name}'.zip'
          $name = ${env:archive_name}
          echo "::set-output name=package_name::$name"
      - uses: actions/upload-artifact@v2
        with:
          name: ${{ steps.packaging.outputs.package_name }}.zip
          path: ${{ steps.packaging.outputs.package_name }}.zip
      - name: Upload Release
        if: startsWith(github.event.ref, 'refs/tags/')
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: ${{ steps.packaging.outputs.package_name }}.zip
          asset_name: ${{ steps.packaging.outputs.package_name }}.zip
          tag: ${{ github.ref }}
          overwrite: true 
