name: Build for Windows with MinGW
on:
  push:
    branches: [ master ]
    tags:
      - 'v*'
  pull_request:
    branches: [ master ]
jobs:
  build-for-windows:
    runs-on: [windows-2019]
    strategy:
      matrix:
        qt_version: [6.2.1]
        qt_arch: [win64_mingw81]
    env:
      executable: atomscistudio
    steps: 
      - name: Install MinGW
        uses: egor-tensin/setup-mingw@v2
        with:
          platform: x64
      - name: Install Qt
        uses: jurplel/install-qt-action@v2.14.0
        with:
          version: ${{ matrix.qt_version }}
          host: 'windows'
          target: 'desktop'
          arch: ${{ matrix.qt_arch }}
          aqtversion: '==2.0.6'
          modules: 'qt3d'
      - name: Install Boost
        uses: MarkusJx/install-boost@v2.1.0
        id: install-boost
        with:
          boost_version: 1.78.0
          platform_version: 2019
          boost_install_dir: 'C:/Program Files (x86)/'
          toolset: mingw
      - name: Download GoogleTest
        shell: powershell
        run: |
          Invoke-WebRequest -Uri https://github.com/google/googletest/archive/refs/tags/release-1.11.0.tar.gz -OutFile release-1.11.0.tar.gz
          tar -xvf release-1.11.0.tar.gz
      - name: Build GoogleTest
        shell: powershell
        run: |
          cmake googletest-release-1.11.0 -B build_gtest -G 'MinGW Makefiles'
          cmake --build build_gtest --config Release
          cmake --install build_gtest
      - name: Download OpenSSL
        shell: powershell
        run: |
          Invoke-WebRequest -Uri https://github.com/openssl/openssl/archive/refs/tags/openssl-3.0.1.tar.gz -OutFile openssl-3.0.1.tar.gz
          tar -xvf openssl-3.0.1.tar.gz
      - name: Build OpenSSL
        shell: powershell
        run: |
          choco install openssl
          choco upgrade openssl.light
      - name: Download libssh2
        shell: powershell 
        run: |
          Invoke-WebRequest -Uri https://github.com/libssh2/libssh2/releases/download/libssh2-1.10.0/libssh2-1.10.0.tar.gz -OutFile libssh2-1.10.0.tar.gz
          tar -xvf libssh2-1.10.0.tar.gz
      - name: Install libssh2
        shell: powershell 
        run: |
          cmake libssh2-1.10.0 -B build_libssh2 -G 'MinGW Makefiles'
          cmake --build build_libssh2
          cmake --install build_libssh2
      - name: Download BLAS
        shell: powershell 
        run: |
          Invoke-WebRequest -Uri http://www.netlib.org/blas/blas-3.10.0.tgz -OutFile blas-3.10.0.tgz
          tar -xvf blas-3.10.0.tgz
      - name: Install BLAS
        run: |
          cmake BLAS-3.10.0 -B build_blas -G "MinGW Makefiles"
          cmake --build build_blas --parallel 4
          cmake --install build_blas
        shell: powershell
      - name: Download LAPACK
        shell: powershell
        run: |
          Invoke-WebRequest -Uri http://www.netlib.org/lapack/lapack-3.8.0.tar.gz -OutFile lapack-3.8.0.tar.gz
          tar -xvf lapack-3.8.0.tar.gz
      - name: Install LAPACK
        run: |
          cmake lapack-3.8.0 -B build_lapack -G 'MinGW Makefiles'
          cmake --build build_lapack --parallel 4
          cmake --install build_lapack
        shell: bash  
      - name: Download OpenBLAS
        shell: powershell
        run: |
          Invoke-WebRequest -Uri https://github.com/xianyi/OpenBLAS/archive/refs/tags/v0.3.19.tar.gz -OutFile v0.3.19.tar.gz
          tar -xvf v0.3.19.tar.gz
      - name: Install OpenBLAS
        run: |
          #cmake OpenBLAS-0.3.19 -B build_openblas -G 'MinGW Makefiles'  
          #cmake --build build_openblas --parallel 4
          #cmake --install build_openblas 
        shell: powershell
      - name: Download SuperLU
        shell: powershell
        run: |
          Invoke-WebRequest -Uri https://github.com/xiaoyeli/superlu/archive/refs/tags/v5.3.0.tar.gz -OutFile v5.3.0.tar.gz
          tar -xvf v5.3.0.tar.gz
      - name: Install SuperLU
        run: |
          cmake superlu-5.3.0 -B build_superlu -G 'MinGW Makefiles' -DCMAKE_Fortran_FLAGS="-fPIC" -DCMAKE_C_FLAGS="-fPIC" -DCMAKE_CXX_FLAGS="-fPIC"
          cmake --build build_superlu --parallel 4
          cmake --install build_superlu
        shell: bash 
      - name: Download armadillo
        shell: powershell
        run: |
          Invoke-WebRequest -Uri https://jztkft.dl.sourceforge.net/project/arma/armadillo-10.8.2.tar.xz -OutFile armadillo-10.8.2.tar.xz
      - name: Extract armadillo
        shell: bash
        # tar in powershell can deal with tar.gz
        # but tar.xz need to be extracted in bash 
        run: |
          tar -xvf armadillo-10.8.2.tar.xz
      - name: Install armadillo
        run: |
          cmake armadillo-10.8.2 -B build_armadillo -G 'MinGW Makefiles' -DCMAKE_INSTALL_PREFIX="C:/Program Files (x86)/armadillo" #-DCMAKE_PREFIX_PATH='C:/Program Files (x86)/LAPACK;C:/Program Files (x86)/BLAS;C:/Program Files (x86)/SuperLU' 
          cmake --build build_armadillo
          cmake --install build_armadillo
        shell: powershell
      - name: Install atomsciflow
        run: |
          git clone https://github.com/deqitang/atomsciflow.git
          cmake atomsciflow -B build_atomsciflow -DBUILD_CMD=OFF -G 'MinGW Makefiles' -DGTEST_ROOT="C:/Program Files (x86)/googletest-distribution" -DCMAKE_PREFIX_PATH='C:/Program Files (x86)/armadillo;C:/Program Files (x86)/libssh2;C:/Program Files (x86)/SuperLU;C:/Program Files (x86)/LAPACK;C:/Program Files (x86)/BLAS'
          cmake --build build_atomsciflow --config Release 
          cmake --install build_atomsciflow
        env:
          BOOST_ROOT: ${{ steps.install-boost.outputs.BOOST_ROOT }}  
        shell: powershell
      - uses: actions/checkout@v2
        with:
          fetch-depth: 1
      - name: Build for Windows with MinGW
        run: |
          cmake -B build_atomscistudio -G 'MinGW Makefiles' -DCMAKE_PREFIX_PATH='C:/Program Files (x86)/armadillo;C:/Program Files (x86)/atomsciflow;C:/Program Files (x86)/LAPACK;C:/Program Files (x86)/BLAS'
          cmake --build build_atomscistudio --config Release
        env:
          BOOST_ROOT: ${{ steps.install-boost.outputs.BOOST_ROOT }}  
        shell: powershell
      - name: packaging
        id: packaging
        shell: powershell
        env:
          archive_name: atomscistudio-${{ matrix.qt_version }}-${{ matrix.qt_arch }}
        run: |
          New-Item -ItemType Directory ${env:archive_name}
          Copy-Item build_atomscistudio\${env:executable}'.exe' ${env:archive_name}\${env:executable}'.exe'
          windeployqt ${env:archive_name}\${env:executable}'.exe' --verbose=2 --compiler-runtime
          ldd ${env:archive_name}\${env:executable}'.exe'
          Copy-Item README.md ${env:archive_name}\README.md
          Copy-Item LICENSE ${env:archive_name}\LICENSE
          Copy-Item NOTICE ${env:archive_name}\NOTICE
          New-Item -ItemType Directory ${env:archive_name}\third_party\license
          Copy-Item third_party\license\* ${env:archive_name}\third_party\license\
          Copy-Item 'C:/Program Files/OpenSSL-Win64/libcrypto-1_1-x64.dll' ${env:archive_name}\
          Copy-Item 'C:/Program Files/OpenSSL-Win64/libssl-1_1-x64.dll' ${env:archive_name}\
          Compress-Archive -Path ${env:archive_name} ${env:archive_name}'.zip'
          $name = ${env:archive_name}
          echo "::set-output name=package_name::$name"
      - uses: actions/upload-artifact@v2
        with:
          name: ${{ steps.packaging.outputs.package_name }}.zip
          path: ${{ steps.packaging.outputs.package_name }}.zip
      - name: Upload Release
        if: startsWith(github.event.ref, 'refs/tags/')
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: ${{ steps.packaging.outputs.package_name }}.zip
          asset_name: ${{ steps.packaging.outputs.package_name }}.zip
          tag: ${{ github.ref }}
          overwrite: true 
